const DEFAULT_ASSISTANT_ID = '5db8d17f-e467-4275-9531-9ccd2c983ff1';
const $ = (sel) => document.querySelector(sel);
const timeline = $('#timeline');
const settingsDialog = $('#settingsDialog');
const keyStorage = 'pink_vapi_public_key';
const assistantStorage = 'pink_vapi_assistant_id';
let callActive = false;
let lastStateBeforeError = 'idle';
let stateFallbackTimer = null;
const seenMessages = new Set();
const STATE = {idle:{label:'Pronta',badge:'Pink em espera',voice:'Pronta para conversar',node:null},listening:{label:'Ouvindo você',badge:'Pink ouvindo',voice:'Ouvindo…',node:'listen'},thinking:{label:'Pensando',badge:'Pink pensando',voice:'Processando pedido…',node:'think'},speaking:{label:'Falando',badge:'Pink falando',voice:'Roberta · ElevenLabs',node:'speak'},executing:{label:'Executando',badge:'Pink executando',voice:'Executando ação…',node:'act'},error:{label:'Atenção',badge:'Verificar voz',voice:'Falha na conexão',node:null}};
function nowLabel(){return new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit'}).format(new Date())}
function addMessage(role,text){if(!text||!timeline)return;const cleaned=String(text).trim();if(!cleaned)return;const key=`${role}:${cleaned}`;if(seenMessages.has(key))return;seenMessages.add(key);if(seenMessages.size>80)seenMessages.delete(seenMessages.values().next().value);const item=document.createElement('div');item.className=`timeline-item ${role}`;item.innerHTML=`<div class="avatar-mini">${role==='assistant'?'P':'V'}</div><div class="bubble"><strong>${role==='assistant'?'Pink':'Você'}</strong><p></p><time>${nowLabel()}</time></div>`;item.querySelector('p').textContent=cleaned;timeline.appendChild(item);timeline.scrollTop=timeline.scrollHeight}
function getConfig(){return{publicKey:localStorage.getItem(keyStorage)||'',assistantId:localStorage.getItem(assistantStorage)||DEFAULT_ASSISTANT_ID}}
function setAgentNode(name){document.querySelectorAll('.agent-node').forEach(node=>node.classList.toggle('active',Boolean(name)&&node.dataset.node===name))}
function setPinkState(state,options={}){const meta=STATE[state]||STATE.idle;const stage=$('#pinkStage');if(!stage)return;if(state!=='error')lastStateBeforeError=state;stage.dataset.state=state;$('#avatarStateText').textContent=meta.label;$('#systemBadge').textContent=meta.badge;$('#voiceStatus').textContent=meta.voice;setAgentNode(meta.node);clearTimeout(stateFallbackTimer);if(options.fallbackMs)stateFallbackTimer=setTimeout(()=>setPinkState(callActive?'listening':'idle'),options.fallbackMs)}
function updateConnectionStatus(configured){if(!configured){callActive=false;setPinkState('idle');$('#voiceStatus').textContent='Aguardando configuração';$('#systemBadge').textContent='Modo laboratório'}else if(!callActive){$('#voiceStatus').textContent='Vapi pronto · Roberta';$('#systemBadge').textContent='Pink online'}}
function normalizeMessage(detail){if(!detail)return null;if(detail.message&&typeof detail.message==='object')return detail.message;if(detail.detail&&typeof detail.detail==='object')return detail.detail;return detail}
function transcriptText(msg){return msg.transcript||msg.text||msg.message?.content||''}
function isFinalTranscript(msg){const t=String(msg.transcriptType||msg.transcript_type||msg.status||'').toLowerCase();if(!t)return true;return t.includes('final')||t==='completed'||t==='done'}
function handleSpeechUpdate(msg){const status=String(msg.status||msg.speechStatus||msg.speech_status||'').toLowerCase();const role=String(msg.role||msg.speaker||'').toLowerCase();if(role==='assistant'){if(/start|speaking|active/.test(status))setPinkState('speaking');if(/stop|end|inactive|finished/.test(status))setPinkState(callActive?'listening':'idle');return}if(role==='user'||role==='customer'){if(/start|speaking|active/.test(status))setPinkState('listening');if(/stop|end|inactive|finished/.test(status))setPinkState('thinking');return}if(/start/.test(status))setPinkState('speaking');if(/stop|end/.test(status))setPinkState(callActive?'listening':'idle')}
function handleVapiMessage(detail){const msg=normalizeMessage(detail);if(!msg||typeof msg!=='object')return;const type=String(msg.type||'').toLowerCase();if(type==='transcript'){const role=String(msg.role||'').toLowerCase();const text=transcriptText(msg);const final=isFinalTranscript(msg);if(role==='user'||role==='customer'){setPinkState(final?'thinking':'listening');if(final)addMessage('user',text)}else if(role==='assistant'){setPinkState('speaking',{fallbackMs:final?1500:0});if(final)addMessage('assistant',text)}return}if(type==='speech-update'){handleSpeechUpdate(msg);return}if(type==='assistant.speechstarted'||type==='assistant-speech-started'){setPinkState('speaking');if(msg.text)addMessage('assistant',msg.text);return}if(type==='user-interrupted'){setPinkState('listening');return}if(type.includes('tool')||type.includes('function'))setPinkState('executing',{fallbackMs:1800})}
function bindWidgetEvents(widget){widget.addEventListener('call-start',()=>{callActive=true;setPinkState('listening');addMessage('assistant','Conexão de voz iniciada. Estou te ouvindo.')});widget.addEventListener('call-end',()=>{callActive=false;setPinkState('idle');addMessage('assistant','Chamada encerrada. Quando quiser, pode falar comigo de novo.')});widget.addEventListener('message',event=>handleVapiMessage(event.detail));widget.addEventListener('speech-start',()=>{if(callActive)setPinkState('listening')});widget.addEventListener('speech-end',()=>{if(callActive)setPinkState('thinking')});widget.addEventListener('error',event=>{console.error('Pink/Vapi error',event.detail);setPinkState('error');addMessage('assistant','Tive um problema com a conexão de voz. Verifique a Public API Key do Vapi e tente novamente.');setTimeout(()=>setPinkState(callActive?lastStateBeforeError:'idle'),2400)})}
function renderVoiceWidget(){const cfg=getConfig();const mount=$('#voiceWidgetMount');mount.innerHTML='';if(!cfg.publicKey){mount.innerHTML=`<div class="empty-state"><div class="mic-orb">🎙️</div><strong>Voz pronta para configurar</strong><p>Adicione a Public API Key do Vapi uma única vez. Ela fica salva somente neste navegador.</p><button id="configureVoiceBtn" class="primary-btn">Configurar voz</button></div>`;$('#configureVoiceBtn').addEventListener('click',openSettings);updateConnectionStatus(false);return}const widget=document.createElement('vapi-widget');widget.setAttribute('public-key',cfg.publicKey);widget.setAttribute('assistant-id',cfg.assistantId);widget.setAttribute('mode','voice');widget.setAttribute('theme','dark');widget.setAttribute('size','full');widget.setAttribute('radius','large');widget.setAttribute('main-label','Falar com a Pink');widget.setAttribute('start-button-text','Iniciar conversa');widget.setAttribute('end-button-text','Encerrar');widget.setAttribute('empty-voice-message','Toque para falar com a Pink');widget.setAttribute('show-transcript','true');mount.appendChild(widget);bindWidgetEvents(widget);updateConnectionStatus(true)}
function openSettings(){const cfg=getConfig();$('#publicKeyInput').value=cfg.publicKey;$('#assistantIdInput').value=cfg.assistantId;settingsDialog.showModal()}
$('#settingsBtn').addEventListener('click',openSettings);
$('#saveSettingsBtn').addEventListener('click',()=>{const key=$('#publicKeyInput').value.trim();const assistant=$('#assistantIdInput').value.trim()||DEFAULT_ASSISTANT_ID;if(key)localStorage.setItem(keyStorage,key);else localStorage.removeItem(keyStorage);localStorage.setItem(assistantStorage,assistant);settingsDialog.close();renderVoiceWidget();addMessage('assistant','Voz ativada. A Pink está configurada para usar a Roberta do ElevenLabs.')});
$('#removeKeyBtn').addEventListener('click',()=>{localStorage.removeItem(keyStorage);localStorage.removeItem(assistantStorage);settingsDialog.close();renderVoiceWidget();addMessage('assistant','Removi a Public API Key deste navegador.')});
$('#clearBtn').addEventListener('click',()=>{timeline.innerHTML='';seenMessages.clear();addMessage('assistant','Sessão limpa. Pode falar comigo.')});
function demoSequence(text){addMessage('user',text);setPinkState('listening');setTimeout(()=>setPinkState('thinking'),900);setTimeout(()=>{setPinkState('speaking');addMessage('assistant','Entendi. Estou no modo ao vivo: ouvindo, pensando e respondendo com a voz Roberta. A próxima etapa liga esses comandos às telas e ações dos seus sistemas.')},1900);setTimeout(()=>setPinkState(callActive?'listening':'idle'),5200)}
$('#demoBtn').addEventListener('click',()=>demoSequence('Pink, me mostra como você reage enquanto eu falo.'));document.querySelectorAll('.quick-commands button').forEach(button=>button.addEventListener('click',()=>demoSequence(button.dataset.command)));
$('#expandPreviewBtn').addEventListener('click',()=>{const card=document.querySelector('.preview-card');if(!document.fullscreenElement)card.requestFullscreen?.();else document.exitFullscreen?.()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&!callActive)setPinkState('idle')});window.addEventListener('load',()=>{setPinkState('idle');setTimeout(renderVoiceWidget,450)});
