'use strict';
const assert=require('node:assert');
const {spawn}=require('node:child_process');
const {chromium,devices}=require('playwright');
const port=Number(process.env.PINK_TEST_PORT||4173),baseUrl=`http://127.0.0.1:${port}`;
const server=spawn(process.execPath,['tests/static-server.cjs'],{stdio:['ignore','pipe','inherit'],env:{...process.env,PINK_TEST_PORT:String(port)}});
function waitForServer(){return new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(new Error('Pink test server timeout')),8000);server.stdout.on('data',c=>{if(String(c).includes('Pink test server')){clearTimeout(timer);resolve()}});server.once('exit',code=>{clearTimeout(timer);if(code!==null&&code!==0)reject(new Error(`Pink test server exited ${code}`))})})}
async function smoke(browser,name,contextOptions){
 const context=await browser.newContext(contextOptions),page=await context.newPage(),pageErrors=[];
 page.on('pageerror',e=>pageErrors.push(String(e?.message||e)));
 await page.goto(baseUrl,{waitUntil:'domcontentloaded',timeout:20000});
 await page.waitForFunction(()=>Boolean(window.PinkCore&&window.PinkPerformance&&window.PinkFoundation&&window.PinkOperatingCore),null,{timeout:12000});
 await page.waitForFunction(()=>Boolean(window.PinkMemoryCore&&window.PinkMemoryCloud),null,{timeout:12000});
 await page.waitForFunction(()=>Boolean(window.PinkSupervisorVoice&&window.PinkNeuralTTS&&window.PinkVoiceCatalog&&window.PinkOpenAI&&window.PinkAIGateway&&window.PinkIntentRouter&&window.PinkAgentHarness),null,{timeout:12000});
 await page.waitForFunction(()=>Boolean(window.PinkCameraRouter&&window.PinkGeminiResearch&&window.PinkTools),null,{timeout:12000});
 await page.waitForFunction(()=>Boolean(window.PinkCommandCenter&&document.getElementById('pinkCommandDock')),null,{timeout:12000});
 await page.waitForFunction(()=>Boolean(window.PinkOrbConsole?.snapshot?.().ready),null,{timeout:15000});
 await page.waitForFunction(()=>Boolean(window.PinkAutonomy&&window.PinkAutonomousEvolution&&window.PinkAutonomyModalHotfix&&document.getElementById('pinkAutonomyOverlay')&&document.getElementById('pinkAutonomyBtn')),null,{timeout:15000});
 const title=await page.title();assert.match(title,/Pink LPS Studio/i,`${name}: title mismatch`);
 const stage=page.locator('#pinkStage');assert.strictEqual(await stage.count(),1,`${name}: Pink stage missing`);assert.ok(await stage.isVisible(),`${name}: Pink stage not visible`);
 const orb=page.locator('#pinkOrbCanvas');assert.strictEqual(await orb.count(),1,`${name}: 3D orb canvas missing`);assert.ok(await orb.isVisible(),`${name}: 3D orb canvas not visible`);
 const waveform=page.locator('#pinkOrbWaveform');assert.ok(await waveform.isVisible(),`${name}: Pink waveform not visible`);
 const input=page.locator('#pinkOrbTextInput');assert.ok(await input.isVisible(),`${name}: Pink text input not visible`);
 const mic=page.locator('#pinkOrbMicBtn');assert.ok(await mic.isVisible(),`${name}: Pink microphone control not visible`);
 const send=page.locator('#pinkOrbSendBtn');assert.ok(await send.isVisible(),`${name}: Pink send control not visible`);
 const orbState=await page.evaluate(()=>window.PinkOrbConsole.snapshot());const orbVersion=await page.evaluate(()=>window.PinkOrbConsole.version);assert.strictEqual(orbState.ready,true,`${name}: orb console not ready`);assert.strictEqual(orbState.state,'idle',`${name}: orb initial state mismatch`);
 assert.strictEqual(orbVersion,'1.2.0',`${name}: orbital version mismatch`);assert.strictEqual(orbState.avatarRendered,false,`${name}: avatar must not render in orbital mode`);assert.ok(orbState.projectCount>=1,`${name}: orbital project registry empty`);assert.strictEqual(orbState.gesture.active,false,`${name}: gesture camera must be opt-in`);assert.strictEqual(orbState.gesture.processing,'on-device',`${name}: gesture processing mode mismatch`);
 const projectCards=page.locator('.pink-orbit-card');assert.strictEqual(await projectCards.count(),orbState.projectCount,`${name}: orbital project card count mismatch`);
 const portrait=page.locator('#pinkStage .portrait');assert.strictEqual(await portrait.isVisible(),false,`${name}: legacy Pink portrait visible behind orbital UI`);
 const gestureButton=page.locator('#pinkOrbGestureBtn');assert.ok(await gestureButton.isVisible(),`${name}: gesture opt-in control missing`);assert.strictEqual(await gestureButton.getAttribute('aria-pressed'),'false',`${name}: gestures must start disabled`);
 const cameraAtBoot=await page.evaluate(()=>Boolean(window.PinkVision?.active));assert.strictEqual(cameraAtBoot,false,`${name}: camera started without explicit user action`);
 const commandDock=page.locator('#pinkCommandDock');assert.strictEqual(await commandDock.count(),1,`${name}: unified command dock missing`);assert.ok(await commandDock.isVisible(),`${name}: unified command dock not visible`);
 const commandButtons=page.locator('#pinkCommandDock [data-pcc]');assert.ok(await commandButtons.count()>=8,`${name}: unified command actions incomplete`);
 const commandSnapshot=await page.evaluate(()=>window.PinkCommandCenter.snapshot());assert.strictEqual(commandSnapshot.version,'13.0.0',`${name}: command center version mismatch`);
 const autonomyOverlay=page.locator('#pinkAutonomyOverlay');
 assert.strictEqual(await autonomyOverlay.isVisible(),false,`${name}: autonomy modal must start closed`);
 await page.locator('#pinkAutonomyBtn').click();
 assert.strictEqual(await autonomyOverlay.isVisible(),true,`${name}: autonomy modal did not open`);
 await page.locator('#pinkAutonomyOverlay [data-pink-close]').click();
 assert.strictEqual(await autonomyOverlay.isVisible(),false,`${name}: autonomy modal X did not close`);
 await page.locator('#pinkAutonomyBtn').click();
 assert.strictEqual(await autonomyOverlay.isVisible(),true,`${name}: autonomy modal second open failed`);
 await page.locator('#pinkAutonomyOverlay [data-pink-tab="evolution"]').click();
 const evolutionCandidateId=await page.evaluate(()=>window.PinkEvolution.addCandidate({kind:'reliability',title:'Smoke: aprovação humana da autoevolução',evidence:'Falha observada em runtime durante browser smoke',priority:'high'}).id);
 await page.waitForFunction(id=>Boolean(document.querySelector(`[data-pink-approve-evolution="${id}"]`)),evolutionCandidateId,{timeout:6000});
 const agreementButton=page.locator(`[data-pink-approve-evolution="${evolutionCandidateId}"]`);assert.ok(await agreementButton.isVisible(),`${name}: autoevolution agreement button missing`);assert.match(await agreementButton.textContent(),/Dar de acordo/i,`${name}: agreement button label mismatch`);
 await agreementButton.click();
 await page.waitForFunction(id=>window.PinkAutonomousEvolution.snapshot().candidates.some(c=>c.id===id&&c.approvedForEvolution===true&&c.status==='approved_for_evolution'),evolutionCandidateId,{timeout:6000});
 const approvedCard=page.locator('.pink-evolution-card.approved').filter({hasText:'Smoke: aprovação humana da autoevolução'});assert.ok(await approvedCard.isVisible(),`${name}: approved evolution card not visible`);assert.match(await approvedCard.textContent(),/Aprovado para evolução/i,`${name}: approved evolution status missing`);
 await page.keyboard.press('Escape');
 assert.strictEqual(await autonomyOverlay.isVisible(),false,`${name}: autonomy modal Escape did not close`);
 const foundation=await page.evaluate(()=>window.PinkFoundation.health());assert.strictEqual(foundation.ok,true,`${name}: foundation health degraded: ${JSON.stringify(foundation)}`);
 const operating=await page.evaluate(()=>window.PinkOperatingCore.snapshot());assert.strictEqual(operating.version,'1.0.0',`${name}: operating core version mismatch`);assert.strictEqual(operating.awareness.currentAgent,'chatgpt-supervisor',`${name}: supervisor identity mismatch`);
 const names=operating.capabilities.map(i=>i.name);assert.ok(names.includes('context.snapshot'),`${name}: context capability missing`);assert.ok(names.includes('health.snapshot'),`${name}: health capability missing`);
 const supervisor=await page.evaluate(()=>({exists:Boolean(window.PinkSupervisorVoice),voiceProvider:window.PinkSupervisorVoice?.voiceProvider||null,tts:window.PinkNeuralTTS?.snapshot?.()||null,voiceConfig:window.PinkPublicConfig?.voice||null,voiceCount:window.PinkVoiceCatalog?.voices?.length||0,openai:window.PinkOpenAI?.getStatus?.()||null,gateway:window.PinkAIGateway?.snapshot?.()||null,intent:Boolean(window.PinkIntentRouter)}));
 assert.strictEqual(supervisor.exists,true,`${name}: supervisor voice missing`);assert.strictEqual(supervisor.voiceProvider,'gemini-tts',`${name}: neural TTS is not supervisor voice provider`);assert.strictEqual(supervisor.tts?.provider,'gemini-tts',`${name}: Gemini TTS client missing`);assert.strictEqual(supervisor.tts?.voice,'Aoede',`${name}: Aoede voice not configured`);assert.strictEqual(supervisor.tts?.endpoint,'pink-tts',`${name}: Pink TTS endpoint mismatch`);assert.strictEqual(supervisor.voiceConfig?.provider,'gemini-tts',`${name}: public voice provider mismatch`);assert.strictEqual(supervisor.voiceCount,30,`${name}: voice catalog must contain 30 Gemini voices`);assert.ok(supervisor.gateway?.providers?.some(p=>p.id==='chatgpt'),`${name}: ChatGPT provider missing from gateway`);assert.ok(supervisor.gateway?.providers?.some(p=>p.id==='gemini-reasoning'&&['connected','healthy','degraded'].includes(p.status)),`${name}: grounded web research provider not connected`);assert.strictEqual(supervisor.intent,true,`${name}: intent router missing`);
 const senses=await page.evaluate(async()=>{
   const timePlan=window.PinkIntentRouter.plan('Pink, que horas são agora?');
   const cameraPlan=window.PinkIntentRouter.plan('Pink, abre a câmera');
   const researchPlan=window.PinkIntentRouter.plan('Pesquise na internet as notícias mais recentes sobre NVIDIA');
   const clock=await window.PinkTools.invoke('runtime-clock','time.current');
   return {timePlan,cameraPlan,researchPlan,clock,cameraTool:window.PinkTools.registry.get('camera')};
 });
 assert.strictEqual(senses.timePlan.intent,'runtime_time',`${name}: time intent mismatch`);assert.strictEqual(senses.timePlan.steps[0].capability,'time.current',`${name}: time capability mismatch`);
 assert.strictEqual(senses.cameraPlan.intent,'camera',`${name}: camera intent mismatch`);assert.strictEqual(senses.cameraPlan.steps[0].capability,'camera.open',`${name}: camera capability mismatch`);assert.strictEqual(senses.cameraTool.health,'healthy',`${name}: camera adapter not attached`);
 assert.strictEqual(senses.researchPlan.intent,'research',`${name}: research intent mismatch`);assert.strictEqual(senses.clock.status,'completed',`${name}: runtime clock invocation failed`);assert.ok(senses.clock.result?.localTime,`${name}: runtime clock returned no local time`);
 const harness=await page.evaluate(()=>window.PinkAgentHarness.snapshot());assert.strictEqual(harness.version,'14.0.0',`${name}: V14 harness version mismatch`);assert.strictEqual(harness.toolBridge,true,`${name}: tool bridge unavailable`);assert.ok(harness.plugins.some(p=>p.id==='github'),`${name}: GitHub plugin missing from harness`);
 const memoryHealth=await page.evaluate(()=>({version:window.PinkMemoryCloud.version,status:window.PinkMemoryCloud.status,health:window.PinkMemoryCloud.health()}));assert.strictEqual(memoryHealth.version,'5.0.0',`${name}: memory version mismatch`);assert.strictEqual(memoryHealth.status,'local-fallback',`${name}: development must not write cloud memory`);assert.strictEqual(memoryHealth.health.ok,true,`${name}: local memory fallback unhealthy`);
 await page.evaluate(()=>window.PinkMemoryCloud.remember({type:'preference',text:'Browser smoke prefere memória persistente',importance:.8}));let recalled=await page.evaluate(()=>window.PinkMemoryCloud.recall('memória persistente',{minScore:.1}));assert.ok(recalled.length>=1,`${name}: browser memory recall failed`);
 if(name==='desktop'){await page.reload({waitUntil:'domcontentloaded'});await page.waitForFunction(()=>Boolean(window.PinkMemoryCloud&&window.PinkSupervisorVoice&&window.PinkNeuralTTS&&window.PinkVoiceCatalog&&window.PinkCommandCenter&&window.PinkAgentHarness&&window.PinkCameraRouter&&window.PinkGeminiResearch&&window.PinkOrbConsole?.snapshot?.().ready&&window.PinkAutonomyModalHotfix),null,{timeout:15000});recalled=await page.evaluate(()=>window.PinkMemoryCloud.recall('memória persistente',{minScore:.1}));assert.ok(recalled.length>=1,`${name}: cross-page memory persistence failed`);assert.ok(await page.locator('#pinkCommandDock').isVisible(),`${name}: command dock lost after reload`);assert.ok(await page.locator('#pinkOrbCanvas').isVisible(),`${name}: orb lost after reload`);assert.strictEqual(await page.locator('#pinkAutonomyOverlay').isVisible(),false,`${name}: autonomy modal reopened itself after reload`)}
 const avatar=await page.evaluate(()=>window.PinkAvatar3D?.snapshot?.()||{mode:'orb-voice',hasModel:false});assert.ok(avatar.mode||avatar.state,`${name}: avatar/fallback state unavailable`);
 const performance=await page.evaluate(()=>window.PinkPerformance.snapshot());assert.ok(performance&&performance.tier,`${name}: performance profile unavailable`);
 const bodyWidth=await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth+2);assert.strictEqual(bodyWidth,true,`${name}: horizontal overflow detected`);
 const fatal=pageErrors.filter(m=>!/ResizeObserver loop/i.test(m));assert.deepStrictEqual(fatal,[],`${name}: page errors: ${fatal.join(' | ')}`);
 console.log(`Browser smoke ${name}: OK (${performance.tier}, orbital ${orbVersion}, ${orbState.projectCount} projects, camera opt-in, avatar hidden, autonomy/evolution approval verified, operational senses ready, core ${operating.version}, memory ${memoryHealth.version}, V14 ${harness.version}, supervisor active, command center ${commandSnapshot.version})`);await context.close();
}
(async()=>{await waitForServer();const browser=await chromium.launch({headless:true});try{await smoke(browser,'desktop',{viewport:{width:1440,height:900}});await smoke(browser,'mobile',{...devices['iPhone 14']})}finally{await browser.close();server.kill('SIGTERM')}})().catch(e=>{server.kill('SIGTERM');console.error(e);process.exit(1)});