(() => {
  'use strict';
  const MAX_STEPS=8, clone=v=>JSON.parse(JSON.stringify(v)), id=()=>`plan_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
  const normalizeStep=(step,index)=>({id:step.id||`step_${index+1}`,order:index+1,title:String(step.title||step.description||`Etapa ${index+1}`).slice(0,140),tool:String(step.tool||'none').slice(0,80),status:step.status||'pending',critical:Boolean(step.critical),approvalRequired:Boolean(step.approvalRequired||step.critical),retryCount:Number(step.retryCount||0),maxRetries:Math.max(0,Math.min(3,Number(step.maxRetries??1))),evidence:[],error:''});
  const create=(goal,steps=[],meta={})=>{if(!String(goal||'').trim())throw new Error('goal_required');const p={id:id(),goal:String(goal).slice(0,500),status:'planned',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),revision:1,meta:{...meta},steps:steps.slice(0,MAX_STEPS).map(normalizeStep),history:[]};p.history.push({at:p.createdAt,type:'created',note:'Plan created'});return p;};
  const next=plan=>plan.steps.find(s=>s.status==='pending'||s.status==='ready')||null;
  const mark=(plan,stepId,status,detail='')=>{const p=clone(plan),step=p.steps.find(s=>s.id===stepId);if(!step)throw new Error('step_not_found');step.status=status;if(status==='failed')step.error=String(detail).slice(0,500);else if(detail)step.evidence.push(String(detail).slice(0,500));p.updatedAt=new Date().toISOString();p.history.push({at:p.updatedAt,type:status,stepId,note:String(detail).slice(0,300)});if(p.steps.every(s=>s.status==='completed'||s.status==='skipped'))p.status='completed';else if(status==='failed')p.status='blocked';else p.status='running';return p;};
  const recovery=(plan,stepId,error='')=>{const p=clone(plan),step=p.steps.find(s=>s.id===stepId);if(!step)throw new Error('step_not_found');step.error=String(error).slice(0,500);if(step.approvalRequired)return{action:'approval',reason:'critical_step_requires_approval'};if(step.retryCount<step.maxRetries)return{action:'retry',reason:'retry_budget_available',retryCount:step.retryCount+1};return{action:'replan',reason:'retry_budget_exhausted'};};
  const replan=(plan,replacementSteps,reason='')=>{const p=clone(plan);p.revision+=1;p.status='planned';p.updatedAt=new Date().toISOString();p.steps=replacementSteps.slice(0,MAX_STEPS).map(normalizeStep);p.history.push({at:p.updatedAt,type:'replan',note:String(reason).slice(0,300)});return p;};
  window.PinkPlanner={create,next,mark,recovery,replan,MAX_STEPS};
})();
