drop policy if exists pink_users_select_self on public.pink_users;
create policy pink_users_select_self on public.pink_users for select to authenticated using (id = (select auth.uid()));
drop policy if exists pink_users_update_self on public.pink_users;
create policy pink_users_update_self on public.pink_users for update to authenticated using (id = (select auth.uid())) with check (id = (select auth.uid()));
drop policy if exists pink_memberships_member_select on public.pink_tenant_memberships;
create policy pink_memberships_member_select on public.pink_tenant_memberships for select to authenticated using (user_id = (select auth.uid()) or public.pink_is_tenant_member(tenant_id));
drop policy if exists pink_sessions_member_all on public.pink_sessions;
create policy pink_sessions_member_all on public.pink_sessions for all to authenticated using (public.pink_is_tenant_member(tenant_id)) with check (public.pink_is_tenant_member(tenant_id) and user_id = (select auth.uid()));
drop policy if exists pink_audit_member_insert on public.pink_audit_log;
create policy pink_audit_member_insert on public.pink_audit_log for insert to authenticated with check (public.pink_is_tenant_member(tenant_id) and (actor_user_id is null or actor_user_id = (select auth.uid())));

create index if not exists pink_memberships_user_idx on public.pink_tenant_memberships(user_id);
create index if not exists pink_relationships_subject_idx on public.pink_relationships(subject_person_id);
create index if not exists pink_relationships_target_user_idx on public.pink_relationships(target_user_id);
create index if not exists pink_aliases_project_idx on public.pink_project_aliases(project_id);
create index if not exists pink_project_memory_project_idx on public.pink_project_memory(project_id);
create index if not exists pink_sessions_tenant_idx on public.pink_sessions(tenant_id);
create index if not exists pink_sessions_user_idx on public.pink_sessions(user_id);
create index if not exists pink_conversations_tenant_idx on public.pink_conversations(tenant_id);
create index if not exists pink_conversations_session_idx on public.pink_conversations(session_id);
create index if not exists pink_memories_user_idx on public.pink_memories(user_id);
create index if not exists pink_memories_person_idx on public.pink_memories(person_id);
create index if not exists pink_memories_project_idx on public.pink_memories(project_id);
create index if not exists pink_observations_session_idx on public.pink_observations(session_id);
create index if not exists pink_actions_session_idx on public.pink_actions(session_id);
create index if not exists pink_audit_actor_idx on public.pink_audit_log(actor_user_id);
create index if not exists pink_devices_user_idx on public.pink_devices(user_id);
create index if not exists pink_evolution_tenant_idx on public.pink_evolution_candidates(tenant_id);
create index if not exists pink_reviews_tenant_idx on public.pink_reviews(tenant_id);
create index if not exists pink_reviews_candidate_idx on public.pink_reviews(candidate_id);
create index if not exists pink_experiments_tenant_idx on public.pink_experiments(tenant_id);
create index if not exists pink_experiments_candidate_idx on public.pink_experiments(candidate_id);
create index if not exists pink_approvals_tenant_idx on public.pink_approvals(tenant_id);
create index if not exists pink_approvals_action_idx on public.pink_approvals(action_id);
create index if not exists pink_approvals_approved_by_idx on public.pink_approvals(approved_by);
create index if not exists pink_deployments_tenant_idx on public.pink_deployments(tenant_id);
create index if not exists pink_deployments_project_idx on public.pink_deployments(project_id);
